### ISSUE TITLE
use const constructor in fromJson factory if there are no fields

### ISSUE THREAD

**Issue by spideythewebhead** [spideythewebhead/data_class_plugin#104]

**Comment by nikosportolos** [comment]
@spideythewebhead I think we can close this.

https://github.com/spideythewebhead/data_class_plugin/blob/5ce3281cc3dac66ed37d9725e872664d965fd195/lib/src/contributors/class/from_json_assist_contributor/from_json_assist_contributor.dart#L115-L120
